version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    stdin_open: true

  backend:
    container_name: backend
    build:
      context: backend
    ports:
      - 4000:4000